lab_tag : ZsRE-Llama2-7b-200 # keep it unique
seq_length: 200 # 200 or 1000
gpus : 0 # Index of available GPUs
lr : 0.0001 # learning rate
experts_step : 10 # Iterative steps for training experts
neruals_step : 20 # Iterative steps for traininging index neurons
theta : 0.65 # Thresholds in the inference phase

mid_hidden : 11008 # llama2-7b:11008  llama2-13b:13824

zsRE_edit_data : ./Data/Edit_zsRE.json
zsRE_forget_data : ./Data/Forget_zsRE.json
zsRE_edit_model : ./Model/zsRE_llama2_7b/


expert_save_path : ./experts/
neruals_save_path : ./indexing_neruals/
merge_neruals : ./nerual_merge/
report_res : ./res/

res : ./res/ # Experiment result address

# Layer to be edited
modify_layer_names : [
    "model.layers.20.mlp.down_proj",
]
